project:
  type: default
editor: visual

format:
  gfm: 
    footer: | 
      Excel materials inspired or sourced from [W3Schools](https://www.w3schools.com/). Lab materials inspired by [Data Nuggets](https://datanuggets.org/).
  docx: 
    footer: | 
      Excel materials inspired or sourced from [W3Schools](https://www.w3schools.com/). Lab materials inspired by [Data Nuggets](https://datanuggets.org/).
    

    
    
    
    
  