project:
  type: default
editor: visual

format:
  docx: 
    df-print: kable
    reference-doc: template.docx
  gfm: 
    df-print: kable

execute: 
  echo: false
  warning: false
  error: false

    
    
    
    
  