---
title: "dss_2024 template"
tbl-cap-location: top
fig-cap-location: bottom
---

#### Featured scientist

### Research Background

### Scientific Question

### Scientific Data

-   which data will you graph to answer the question?
    -   independent and dependent variables
-   Graphs of data

### Interpret the data

-   make a claim that answers the scientific question
-   What evidence was used to write your claim?
-   Explain your reasoning and why the evidence supports your claim

### Next steps as a scientist

-   Science is an ongoing process. What new question do you think should be investigated?
-   What future data should be collected to answer your question?
    -   Independent variables/dependent variables
-   For each variable, explain why you included it and how it could be measured
-   What hypothesis are you testing in your experiment?

### References

::: {#refs}
:::

### Before you leave

Fill out the [Weekly Feedback Form](https://forms.gle/RCWtYoAtQGNd8JL38).

Excel materials inspired or sourced from [W3Schools](https://www.w3schools.com/). Lab materials inspired by [Data Nuggets](https://datanuggets.org/).
